config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root "movies#index"
  resources :movies do
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end

get "movies/filter/:filter" => "movies#index", as: :filtered_movies


resource :session, only: [:new,:create,:destroy]

get "signin" => "sessions#new"

resources :users

get "signup" => "users#new"


 end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %>
    <%= link_to "The Pragmatic Studio", "https://skysystemz.com" %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= image_tag("logo.png") %>
    <ul class="left">
      <li>
        <%= link_to "All Movies", movies_path %>
      </li>
      <li>
        <%= link_to "Hits", filtered_movies_path(:hits)%>
      </li>
      <li>
        <%= link_to "Flops", filtered_movies_path(:flops)%>
      </li>
      <li>
        <%= link_to "Upcoming", filtered_movies_path(:upcoming), class: "active" %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Log-Out", session_path,
                data: { turbo_method: :delete },
                class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_session_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>